In [4]:
import numpy as np
a=np.array([[1,2,3],[2,4,5],[5,7,8],[3,4,5]])
print("a:\n=",a)
b=np.array([[4,5,6],[3,5,7],[6,3,8],[7,9,9]])
print("b:\n=",b)
c=(a*b)+b
print("c:\n=",c)

a:
= [[1 2 3]
 [2 4 5]
 [5 7 8]
 [3 4 5]]
b:
= [[4 5 6]
 [3 5 7]
 [6 3 8]
 [7 9 9]]
c:
= [[ 8 15 24]
 [ 9 25 42]
 [36 24 72]
 [28 45 54]]


In [21]:
v=np.append(a,[10,3 ,4], axis=0)

ValueError: all the input arrays must have same number of dimensions